# feeder
feeder: feeders.feeder.Feeder
test_feeder_args:
  data_path: ./data/ntu120/xsub/val_data_joint_bone_motion_cut_150.npy
  label_path: ./data/ntu120/xsub/val_label.pkl
  debug: False

# model
model: model.agcn_stc_sl.Model
model_args:
  num_class: 120
  num_point: 25
  num_person: 2
  graph: graph.ntu_rgb_d_A.Graph
  graph_args:
    labeling_mode: 'spatial'

# test
phase: test
device: [8, 9]
test_batch_size: 256
weights: ./runs/ntu120_xsub_agcn_joint_bone_motion_cut_150-59-118140.pt

work_dir: ./work_dir/ntu120/xsub/agcn_test_joint_bone_motion_cut_150
model_saved_name: ./runs/ntu120_xsub_agcn_test_joint_bone_motion_cut_150
save_score: True
