work_dir: ./work_dir/ntu/xsub/agcn_joint_bone_cut_150
model_saved_name: ./runs/ntu_cs_agcn_joint_bone_cut_150
# feeder
feeder: feeders.feeder.Feeder
train_feeder_args:
  data_path: ./data/ntu/xsub/train_data_joint_bone_cut_150.npy
  label_path: ./data/ntu/xsub/train_label.pkl
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  random_rot: False
  window_size: -1
  normalization: False

test_feeder_args:
  data_path: ./data/ntu/xsub/val_data_joint_bone_cut_150.npy
  label_path: ./data/ntu/xsub/val_label.pkl

# model
model: model.agcn_stc_sl.Model
model_args:
  num_class: 60
  num_point: 25
  num_person: 2
  graph: graph.ntu_rgb_d_A.Graph
  graph_args:
    labeling_mode: 'spatial'

#optim
weight_decay: 0.0002
base_lr: 0.1
step: [30, 40]
warm_up_epoch: 5

# training
device: [5, 6]
batch_size: 32
test_batch_size: 32
num_epoch: 50
nesterov: True

